---
- name: Day 1 Operations - EC2 Linux Baseline
  # The 'env_prod' group was automatically created by the dynamic inventory
  # based on an EC2 tag of Key="Environment", Value="prod"
  hosts: env_prod
  become: true
  tasks:
    - name: Update all packages (RedHat / Amazon Linux)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update all packages (Ubuntu / Debian)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Set system timezone to SGT
      community.general.timezone:
        name: Asia/Singapore